// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearSearch() {
  return window['go']['app']['App']['ClearSearch']();
}

export function CloseTikTokBrowser() {
  return window['go']['app']['App']['CloseTikTokBrowser']();
}

export function ConfirmLoggedIn() {
  return window['go']['app']['App']['ConfirmLoggedIn']();
}

export function DBSmokeTest() {
  return window['go']['app']['App']['DBSmokeTest']();
}

export function DiagDOM() {
  return window['go']['app']['App']['DiagDOM']();
}

export function DiagNetwork() {
  return window['go']['app']['App']['DiagNetwork']();
}

export function DiagRuntime() {
  return window['go']['app']['App']['DiagRuntime']();
}

export function DiagUA() {
  return window['go']['app']['App']['DiagUA']();
}

export function Emit(arg1, arg2) {
  return window['go']['app']['App']['Emit'](arg1, arg2);
}

export function GetAppInfo() {
  return window['go']['app']['App']['GetAppInfo']();
}

export function GetLoginState() {
  return window['go']['app']['App']['GetLoginState']();
}

export function GetLoginURL() {
  return window['go']['app']['App']['GetLoginURL']();
}

export function GetRuntimeStatus() {
  return window['go']['app']['App']['GetRuntimeStatus']();
}

export function GetSettings() {
  return window['go']['app']['App']['GetSettings']();
}

export function GetTikTokBrowserState() {
  return window['go']['app']['App']['GetTikTokBrowserState']();
}

export function LegacyProfiles() {
  return window['go']['app']['App']['LegacyProfiles']();
}

export function OpenLoginWindow() {
  return window['go']['app']['App']['OpenLoginWindow']();
}

export function OpenTikTokBrowser() {
  return window['go']['app']['App']['OpenTikTokBrowser']();
}

export function OpenTikTokSearch(arg1) {
  return window['go']['app']['App']['OpenTikTokSearch'](arg1);
}

export function PageInfo() {
  return window['go']['app']['App']['PageInfo']();
}

export function PingEvent(arg1) {
  return window['go']['app']['App']['PingEvent'](arg1);
}

export function ProbeLoginState() {
  return window['go']['app']['App']['ProbeLoginState']();
}

export function RunScript(arg1) {
  return window['go']['app']['App']['RunScript'](arg1);
}

export function SearchKeyword(arg1) {
  return window['go']['app']['App']['SearchKeyword'](arg1);
}

export function SearchResults() {
  return window['go']['app']['App']['SearchResults']();
}

export function SearchState() {
  return window['go']['app']['App']['SearchState']();
}

export function SetEmitter(arg1) {
  return window['go']['app']['App']['SetEmitter'](arg1);
}

export function SetSettings(arg1) {
  return window['go']['app']['App']['SetSettings'](arg1);
}

export function Shutdown(arg1) {
  return window['go']['app']['App']['Shutdown'](arg1);
}

export function StartSearch(arg1, arg2) {
  return window['go']['app']['App']['StartSearch'](arg1, arg2);
}

export function Startup(arg1) {
  return window['go']['app']['App']['Startup'](arg1);
}

export function StopSearch() {
  return window['go']['app']['App']['StopSearch']();
}

export function WaitBrowserReady(arg1) {
  return window['go']['app']['App']['WaitBrowserReady'](arg1);
}

export function WaitPageReady(arg1) {
  return window['go']['app']['App']['WaitPageReady'](arg1);
}
