// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseMainBrowser() {
  return window['go']['app']['App']['CloseMainBrowser']();
}

export function CloseSearchBrowser() {
  return window['go']['app']['App']['CloseSearchBrowser']();
}

export function ConfirmLoggedIn() {
  return window['go']['app']['App']['ConfirmLoggedIn']();
}

export function DBSmokeTest() {
  return window['go']['app']['App']['DBSmokeTest']();
}

export function Emit(arg1, arg2) {
  return window['go']['app']['App']['Emit'](arg1, arg2);
}

export function GetAppInfo() {
  return window['go']['app']['App']['GetAppInfo']();
}

export function GetLoginState() {
  return window['go']['app']['App']['GetLoginState']();
}

export function GetLoginURL() {
  return window['go']['app']['App']['GetLoginURL']();
}

export function GetMainBrowserState() {
  return window['go']['app']['App']['GetMainBrowserState']();
}

export function GetRuntimeStatus() {
  return window['go']['app']['App']['GetRuntimeStatus']();
}

export function GetSearchBrowserState() {
  return window['go']['app']['App']['GetSearchBrowserState']();
}

export function GetSettings() {
  return window['go']['app']['App']['GetSettings']();
}

export function OpenLoginWindow() {
  return window['go']['app']['App']['OpenLoginWindow']();
}

export function OpenMainBrowser() {
  return window['go']['app']['App']['OpenMainBrowser']();
}

export function OpenSearchBrowser(arg1) {
  return window['go']['app']['App']['OpenSearchBrowser'](arg1);
}

export function PageInfo(arg1) {
  return window['go']['app']['App']['PageInfo'](arg1);
}

export function PingEvent(arg1) {
  return window['go']['app']['App']['PingEvent'](arg1);
}

export function ProbeLoginState() {
  return window['go']['app']['App']['ProbeLoginState']();
}

export function RunScript(arg1, arg2) {
  return window['go']['app']['App']['RunScript'](arg1, arg2);
}

export function SearchKeyword(arg1) {
  return window['go']['app']['App']['SearchKeyword'](arg1);
}

export function SetEmitter(arg1) {
  return window['go']['app']['App']['SetEmitter'](arg1);
}

export function SetSettings(arg1) {
  return window['go']['app']['App']['SetSettings'](arg1);
}

export function Shutdown(arg1) {
  return window['go']['app']['App']['Shutdown'](arg1);
}

export function Startup(arg1) {
  return window['go']['app']['App']['Startup'](arg1);
}

export function WaitBrowserReady(arg1, arg2) {
  return window['go']['app']['App']['WaitBrowserReady'](arg1, arg2);
}
